<?php
/**
 *
 */

namespace app\commands;

use app\models\Stock;
use yii\console\Controller;
use yii\console\ExitCode;

/**
 */
class StockController extends Controller
{

    public $isAll = false;
    public $message;

    public function beforeAction($action)
    {
        $this->color = true;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function options($actionID)
    {
        return ['isAll'];
    }

    public function actionIndex()
    {
        $query = Stock::find();

        $stocks = null;

        if ($this->isAll) {
            $stocks = $query->all();
        } else {
            $stocks = $query->limit(10)->all();
        }

        foreach ($stocks as $stock){
            var_dump($stock->id . PHP_EOL);
            var_dump($stock->name. 'name' . PHP_EOL);
            var_dump($stock->codec . PHP_EOL);
            var_dump("________________");
        }

    }

    public function actionCreate()
    {
        $name = $this->Input("Name Kiriting ", true, 'Name kiritish majburiy');

        $codec = $this->Input("Codec Kiriting ", true, 'Codec kiritish majburiy');

        $stock = Stock::createStock($name, $codec);

        if (!$stock) {
            var_dump('Error');
            return ExitCode::DATAERR;
        }
        var_dump('successful');
        return ExitCode::OK;
    }

    public function actionUpdate()
    {


    }

    public function actionView()
    {

    }

    public function Input($message, $required = false, $error = 'Please Enter Value')
    {
        return $this->prompt($message, [
            'required' => (bool)$required,
            'error' => $error
        ]);
    }

}
