<?php
/*
 *
 */

namespace app\commands;

use app\models\Stock;
use app\models\Transaction;
use yii\console\Controller;

/**
 *
 */

class TransactionController extends Controller
{

    public $isAll;

    public  function beforeAction($action)
    {
        $this->color = true;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function options($actionID)
    {
        return ['isAll'];
    }

    public function actionIndex()
    {

        $query = Transaction::find();

        $stocks = null;

        if ($this->isAll) {
            $stocks = $query->all();
        } else {
            $stocks = $query->limit(10)->all();
        }

        foreach ($stocks as $stock){
            var_dump($stock->id . PHP_EOL);
            var_dump($stock->price. 'price' . PHP_EOL);
            var_dump($stock->seller_id . 'seller_id'. PHP_EOL);
            var_dump($stock->buyer_id . 'buyer_id'. PHP_EOL);
            var_dump("________________");
        }

    }

}
